module.exports = function(Handlebars) {

return Handlebars.template({"compiler":[7,">= 4.0.0"],"main":function(container,depth0,helpers,partials,data) {
    var helper;

  return "<!DOCTYPE html><html><head><link rel=\"stylesheet\" type=\"text/css\" href=\"/static/css/bootstrap.min.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"/static/css/bundle.css\"><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"><script src=\"/static/js/bundle.js\"></script><title>"
    + container.escapeExpression(((helper = (helper = helpers.title || (depth0 != null ? depth0.title : depth0)) != null ? helper : helpers.helperMissing),(typeof helper === "function" ? helper.call(depth0 != null ? depth0 : {},{"name":"title","hash":{},"data":data}) : helper)))
    + "</title></head><body class=\"container-fluid\"><nav><ul><li data-nav=\"top\">A + C</li><li data-nav=\"event-info\">Event Info</li><li data-nav=\"registry\">Registry</li><li data-nav=\"rehearsal\">Rehearsal Party</li><li data-nav=\"accomodations\">Accomodations</li><li data-nav=\"rsvp\">RSVP</li><li data-nav=\"about\">About Us</li></ul></nav><div data-content=\"top\" class=\"row top block\"><div class=\"col-sm-offset-1 col-sm-6 block\"><div><div class=\"names\">Alex and Chris</div><div class=\"date\">09.24.2016</div></div></div><div class=\"col-sm-5\"></div></div><div data-content=\"event-info\" class=\"row event-info block\"><div class=\"heading\">Event Info</div><div class=\"col-sm-offset-8 col-sm-3 text-left\"><div class=\"sub-heading\">Kirkbride Hall</div><div class=\"text\">700 Cottageview Dr.</div><div class=\"text\">Traverse City, MI 49684</div><div class=\"pink-text\">Ceremony at 4:30pm</div><div class=\"text\">Dinner and Dancing to follow</div><div class=\"pink-text\">Please join us at our Rehearsal Party on Friday!</div><div class=\"text\">Click here for more info</div></div></div><div data-content=\"registry\" class=\"row block registry\"><div class=\"heading\">Registry</div><div>Macy's</div><div>Amazon</div><div>Target</div></div><div data-content=\"rehearsal\" class=\"row rehearsal block\"><div class=\"heading\">Rehearsal Party</div><div class=\"col-sm-offset-3 col-sm-6 text-center\"><div><span>Friday</span><span class=\"pinkball\"></span><span>9.23.2016</span><span class=\"pinkball\"></span><span>7:00pm</span></div><div><div>Please join us for dinner and celebration</div><div>on Friday night before our wedding.</div></div><div>Location: TBD</div></div></div><div data-content=\"accomodations\" class=\"row block accomodations\"><div class=\"col-sm-6 col-sm-offset-3\"><div class=\"heading\">Accomodations and Travel</div><div class=\"row\"><div class=\"col-sm-2\">Hotels:</div><div class=\"col-sm-10\">TBD</div></div><div class=\"row\"><div class=\"col-sm-2\">Airports:</div><div class=\"col-sm-10\">Cherry Capital Airport (TVC)</div></div><div class=\"row\"><div class=\"col-sm-2\"></div><div class=\"col-sm-10\">Gerry R. Ford Airport (GRR)</div></div></div></div><div data-content=\"rsvp\" class=\"row block rsvp\"><div class=\"heading\">RSVP</div><div class=\"text-center\">Coming Soon!</div></div><div data-content=\"about\" class=\"row block about\"><div class=\"heading\">About Us</div><div class=\"col-sm-offset-3 col-sm-6 text\"><div>In 2011, Alex and Chris met playing soccer in Chicago.</div><div>Alex watched Chris hurt his left knee ( the first time ).</div><div>Chris asked Alex out after group-hanging at a ping pong bar.</div><div>Now they have two cats and live in Grand Rapids, MI where they are plotting to start a farm.</div></div></div></body></html>";
},"useData":true});

};